### ISSUE TITLE
I wonder if 64/128 could be solved with Generics

### ISSUE THREAD

**Issue by nLight** [DmitriiKh/FastBurgAlgorithmLibrary#1]
https://github.com/DmitriiKh/FastBurgAlgorithmLibrary/blob/529402a013636539c209e5b1972b2d56279d1bef/FastBurgAlgorithmLibrary/FastBurgAlgorithm64.cs#L10

Documentation https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/introduction-to-generics

There's only one difference in those to classes:
```diff
- var denominator = 0.000000000000000000000000001M;
+ var denominator = double.Epsilon;
```
That we could resolve by injecting `denominator` into constructor or we could test type `T` and decide on spot. Everything else is `double` vs `decimal` that will become `T`.

So it should be possible to boil it down to:
```c#
FastBurg<double> algorithm64 = new FastBurg<double>();
FastBurg<decimal> algorithm128 = new FastBurg<decimal>();
```

**Comment by DmitriiKh** [comment]
Thank you very much for the comment.
New branch "Generic" has been made to realize the suggested approach. 

Using Generics allows to have only one version of the class instead of two. This potentially can make the library more maintainable.
Nevertheless it occurred to have two disadvantages: a little bit cumbersome arithmetic operations on Generics and some impact to performance.
The arithmetic operations on Generics are not supported by C# at this moment. This problem solved by using static class Operations<T> which replaces

`var result = a + b * c;` 

with 

`var result = _operations.Add(a, _operations.Multiply(b, c));`

Also using constants requires changing their types so 

`var newResult = 2 * result;`

becomes

`var newResult = _operations.Multiply((T) Convert.ChangeType(2, typeof(T)), result);`

Unfortunately it makes the code less readable.

The second disadvantage is the twice lower performance for 64bit (double) internal variables size. 

All and all this is why I'm not sure if the current "Generic" branch is better then "master" branch but it's definitely better then "DataCS" branch where 'dynamic' types were implemented.

Any comments will be appreciated
